export default {
  S: {
    '#': 'Punktgewinn',
    '+': 'Guter Aufschlag (nur noch Highball beim Gegner möglich)',
    '!': 'Akzeptabler Aufschlag (gn. Zuspieler werden Optionen minimiert)',
    '/': 'Sehr guter Aufschlag (kein gn. Angriff möglich)',
    '-': 'Schlechter Aufschlag (gute oder perfekte gn. Annahme)',
    '=': 'Fehler (Punkt Gegner)',
  },
  R: {
    '#': 'Perfekte Annahme',
    '+': 'Gute Annahme (nähe perfekter Zuspielsituation)',
    '!': 'Ausreichende Annahme (Zuspielpos. versetzt)',
    '/': 'Sehr schlechte Annahme (kein Angriff möglich)',
    '-': 'Schlechte Annahme (nur Highball möglich)',
    '=': 'Fehler (Punkt Gegner)',
  },
  A: {
    '#': 'Punktgewinn',
    '+': 'Guter Angriff (nächste eigene Angriffschance)',
    '!': 'Angriff in den Block mit eigener nächsten Angriffschance (Recycle)',
    '/': 'Angriff in den Block (direkter gn.Punkt)',
    '-': 'Schlechter Angriff (nächste Angriffschance beim Gegner)',
    '=': 'Fehler (Punkt Gegner)',
  },
  B: {
    '#': 'Punktgewinn',
    '+': 'Guter Blocktouch (nächste eigene Angriffschance)',
    '!': 'Ball abgewehrt (Recycle des Gegners)',
    '/': 'Blocktouch mit Punktfolge Gegner (Block angeschlagen)',
    '-': 'Schlechter Blocktouch (nächste Angriffschance beim Gegner)',
    '=': 'Fehler (Punkt Gegner)',
  },
  D: {
    '#': 'Perfekte Abwehr',
    '+': 'Gute Abwehr (nähe perfekter Zuspielsituation)',
    '!': 'Ausreichende Abwehr (Zuspielpos. versetzt)',
    '/': 'Sehr schlechte Abwehr (kein Angriff möglich)',
    '-': 'Schlechte Abwehr (nur Highball möglich)',
    '=': 'Fehler (Punkt Gegner)',
  },
  E: {
    '#': 'Perfektes Zuspiel',
    '+': 'Gutes Zuspiel (minimale Ungenauigkeiten)',
    '!': 'Ausreichendes Zuspiel (größere Streuung)',
    '/': 'Sehr schlechtes Zuspiel (kein Angriff möglich, ggf Z zum Gegner)',
    '-': 'Schlechtes Zuspiel (grobe Abweichung des Zuspiels)',
    '=': 'Fehler (Punkt Gegner)',
  },
  F: {
    '#': 'Perfekter Dankeball',
    '+': 'Guter Dankeball (nähe perfekter Zuspielsituation)',
    '!': 'Ausreichender Dankeball (Zuspielpos. versetzt)',
    '/': 'Sehr schlechter Dankeball (kein Angriff möglich)',
    '-': 'Schlechter Dankeball (nur Highball möglich)',
    '=': 'Fehler (Punkt Gegner)',
  },
};
