export enum SVB_APP_ROUTES {
  report = 'report',
  reportDetail = 'report/details',
  reportDetailId = 'report/details/:id',
  roationPlaner = 'rotation-planer',
  create = 'create',
  editGame = 'edit-game',
  teams = 'teams',
  games = 'games',
  dataentry = 'dataentry',
  login = 'login',
  root = '/',
  user = 'user',
  playerProgress = 'player-progress',
  playerDetailStats = 'player-stats',
}
